language: php

php:
  - '5.6'
  - '7.0'
  - '7.1'
  - '7.2'

before_script:
  - travis_retry composer self-update
  - travis_retry composer update ${COMPOSER_FLAGS} --no-interaction
  - mkdir -p build/logs

script:
    - vendor/bin/phpunit --coverage-clover=build/logs/clover.xml
